language: ruby
cache: bundler
sudo: false

before_script:
  - bundle exec rake db:create

script: 'bundle exec rake'

gemfile:
  - gemfiles/Gemfile
  - gemfiles/Gemfile.activemodel-serializers-xml
  - gemfiles/Gemfile.rails-4.2.rb
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1
  - 2.0.0
  - rbx
  - jruby-9.1.2.0

env:
  - DB=postgres
  - DB=mysql

matrix:
  allow_failures:
    - rvm: rbx
      gemfile: Gemfile
    - rvm: rbx
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml
  exclude:
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/40dc875af26f64f39090
